apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/robcarmo/argocd.git
    targetRevision: localdev
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd