apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base/repository.yaml
- base/amb-init-config
- base/secrets.yaml
- base/argocd.yaml
- base/local-services.yaml
- https://github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.3.0

patchesStrategicMerge:
- overlays/service.yaml
- overlays/argocd-secret.yaml

patchesJson6902:
- path: overlays/deploy-command.yaml
  target:
    group: apps
    kind: Deployment
    name: argocd-server
    version: v1

namespace: argocd
