apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:robcarmo/argocd.git
    targetRevision: HEAD
    path: argocdconfig
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true