apiVersion: v1
kind: Secret
metadata:
  name: argoproj-ssh-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  - url: git@github.com:robcarmo/argocd.git
    sshPrivateKey: |
      -----BEGIN OPENSSH PRIVATE KEY-----
      b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
      QyNTUxOQAAACC037/q4MWHdCAg5g/qiTUDtJvrj07npLw5XAcm64luNgAAAJiieLfponi3
      6QAAAAtzc2gtZWQyNTUxOQAAACC037/q4MWHdCAg5g/qiTUDtJvrj07npLw5XAcm64luNg
      AAAEC8rQsqAdCMs9o/glSK4/BLmvXgFMLHzcWlUOO7ufZU4rTfv+rgxYd0ICDmD+qJNQO0
      m+uPTuekvDlcBybriW42AAAAE3JvYmNhcm1vZkBnbWFpbC5jb20BAg==
      -----END OPENSSH PRIVATE KEY-----